# Site settings
title: Cannatella version of The Wilke Lab
address: The University of Texas at Austin
email: catfish@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  Department of Integrative Biology<br>
  Institute for Cellular and Molecular Biology<br>
  2500 Speedway, A4800<br>
  Room: MBB 3.232
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  
instagram_username: 

# Build settings
markdown: kramdown
